[metadata]
catalog_number = "MMBST-84163"
release_year = "2015"
media_type = "33 RPM"
audio_channels = "Stereo"
provenance = "PBTHAL 2015"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "Hat and Beard"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Something Sweet, Something Tender"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Gazzelloni"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "Out to Lunch"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Straight Up and Down"

[children]
[[children.files]]
file = "Eric Dolphy - (1964) Out to Lunch [2015, MMBST-84163, 33 RPM, Stereo, PBTHAL 2015]/1.01 Hat and Beard.flac"
disc_number = 1
track_number = 1

[[children.files]]
file = "Eric Dolphy - (1964) Out to Lunch [2015, MMBST-84163, 33 RPM, Stereo, PBTHAL 2015]/1.02 Something Sweet, Something Tender.flac"
disc_number = 1
track_number = 2

[[children.files]]
file = "Eric Dolphy - (1964) Out to Lunch [2015, MMBST-84163, 33 RPM, Stereo, PBTHAL 2015]/1.03 Gazzelloni.flac"
disc_number = 1
track_number = 3

[[children.files]]
file = "Eric Dolphy - (1964) Out to Lunch [2015, MMBST-84163, 33 RPM, Stereo, PBTHAL 2015]/2.01 Out to Lunch.flac"
disc_number = 2
track_number = 1

[[children.files]]
file = "Eric Dolphy - (1964) Out to Lunch [2015, MMBST-84163, 33 RPM, Stereo, PBTHAL 2015]/2.02 Straight Up and Down.flac"
disc_number = 2
track_number = 2
