output_directory = "/archive/Music"

[convert]
ffmpeg_command = "ffmpeg"
target_format = "flac"
sample_rate = 44100
sample_format = "s16"

[replaygain]
rsgain_command = "rsgain"
album_gain = true
target_lufs = -18.0
clip_mode = "disabled"

[metadata]

[children]
modules = [
	"Art Blakey - (1959) Art Blakey and The Jazz Messengers [Moanin']",
	"Art Blakey - (1965) Free for All",
	"John Coltrane - (1965) A Love Supreme",
	"Lee Morgan - (1964) The Sidewinder",
	"Lee Morgan - (1966) Search for the New Land",
	"McCoy Tyner - (1967) The Real McCoy",
	"Pete La Roca - (1965) Basra",
	"Pink Floyd - (1975) Wish You Were Here",
	"Wayne Shorter - (1964) Night Dreamer",
	"Wayne Shorter - (1966) Speak No Evil",
	"Yes - (1972) Close to the Edge"
]
