output_directory = "/archive/Music"

[convert]
ffmpeg_command = "ffmpeg"
target_format = "flac"
sample_rate = 44100
sample_format = "s16"

[replaygain]
rsgain_command = "rsgain"
album_gain = true
target_lufs = -18.0
clip_mode = "disabled"

[metadata]

[children]
modules = [
	"Art Blakey - (1959) Art Blakey and The Jazz Messengers [Moanin']",
	"Art Blakey - (1961) A Night in Tunisia",
	"Art Blakey - (1965) Free for All",
	"Charles Mingus - (1959) Mingus Ah Um",
	"Charles Mingus - (1960) Blues & Roots",
	"Grachan Moncur III - (1964) Evolution",
	"Grant Green - (1965) Idle Moments",
	"Herbie Hancock - (1965) Maiden Voyage",
	"Herbie Hancock - (1973) Head Hunters",
	"Joe Henderson - (1963) Page One",
	"John Coltrane - (1965) A Love Supreme",
	"Lee Morgan - (1964) The Sidewinder",
	"Lee Morgan - (1966) Search for the New Land",
	"Lee Morgan - (1967) Cornbread",
	"Lee Morgan - (1978) Lee Morgan All-Star Sextet",
	"McCoy Tyner - (1967) The Real McCoy",
	"Miles Davis - (1959) Kind of Blue",
	"Pete La Roca - (1965) Basra",
	"Pink Floyd - (1975) Wish You Were Here",
	"Steely Dan - (1977) Aja",
	"Wayne Shorter - (1964) Night Dreamer",
	"Wayne Shorter - (1966) Speak No Evil",
	"Wayne Shorter - (1966) The All Seeing Eye",
	"Wayne Shorter - (1967) Adam's Apple",
	"Yes - (1971) Fragile",
	"Yes - (1972) Close to the Edge"
]
