[metadata]
catalog_number = "MFSL 2-439"
release_year = "2014"
media_type = "33 RPM"
audio_channels = "Stereo"
provenance = "Фитоседан"

[[discs]]
[[discs.tracks]]
[discs.tracks.metadata]
title = "Pharaoh's Dance"

[[discs]]
[[discs.tracks]]
[discs.tracks.metadata]
title = "Bitches Brew"

[[discs]]
[[discs.tracks]]
[discs.tracks.metadata]
title = "Spanish Key"

[[discs.tracks]]
[discs.tracks.metadata]
title = "John McLaughlin"

[[discs]]
[[discs.tracks]]
[discs.tracks.metadata]
title = "Miles Runs the Voodoo Down"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Sanctuary"

[children]
[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/A. Pharaoh's Dance.dsf"
disc_number = 1
track_number = 1

[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/B. Bitches Brew.dsf"
disc_number = 2
track_number = 1

[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/C1. Spanish Key.dsf"
disc_number = 3
track_number = 1

[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/C2. John McLaughlin.dsf"
disc_number = 3
track_number = 2

[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/D1. Miles Runs The Voodoo Down.dsf"
disc_number = 4
track_number = 1

[[children.files]]
file = "[DSD256] Miles Davis - Bitches Brew (1970, 2014, MFSL 2-439)/D2. Sanctuary.dsf"
disc_number = 4
track_number = 2
