[metadata]
catalog_number = "MMBST-84220"
release_year = "2016"
media_type = "33 RPM"
audio_channels = "Stereo"
provenance = "PBTHAL 2020"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "The Cape Verdean Blues"

[[discs.tracks]]
[discs.tracks.metadata]
title = "The African Queen"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Pretty Eyes"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "Nutville"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Bonita"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Mo' Joe"

[children]
[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/1.01 The Cape Verdean Blues.flac"
disc_number = 1
track_number = 1

[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/1.02 The African Queen.flac"
disc_number = 1
track_number = 2

[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/1.03 Pretty Eyes.flac"
disc_number = 1
track_number = 3

[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/2.01 Nutville.flac"
disc_number = 2
track_number = 1

[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/2.02 Bonita.flac"
disc_number = 2
track_number = 2

[[children.files]]
file = "Horace Silver, J. J. Johnson - (1965) The Cape Verdean Blues [2016, MMBST-84220, 33 RPM, Stereo, PBTHAL 2020]/2.03 Mo' Joe.flac"
disc_number = 2
track_number = 3
