[metadata]
catalog_number = "Unknown"
release_year = "2013"
media_type = "Digital"
audio_channels = "Stereo"
provenance = "e-onkyo"

[[discs]]
[[discs.tracks]]
[discs.tracks.metadata]
title = "Red Clay"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Delphia"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Suite Sioux"

[[discs.tracks]]
[discs.tracks.metadata]
title = "The Intrepid Fox"

[children]
[[children.files]]
file = "Freddie Hubbard - Red Clay (1970, CTI) [24-192]/01 - Red Clay.flac"
disc_number = 1
track_number = 1

[[children.files]]
file = "Freddie Hubbard - Red Clay (1970, CTI) [24-192]/02 - Delphia.flac"
disc_number = 1
track_number = 2

[[children.files]]
file = "Freddie Hubbard - Red Clay (1970, CTI) [24-192]/03 - Suite Sioux.flac"
disc_number = 1
track_number = 3

[[children.files]]
file = "Freddie Hubbard - Red Clay (1970, CTI) [24-192]/04 - The Intrepid Fox.flac"
disc_number = 1
track_number = 4
