[metadata]
catalog_number = "MMBST-84185"
release_year = "2019"
media_type = "33 RPM"
audio_channels = "Stereo"
provenance = "PBTHAL 2019"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "Song for My Father"

[[discs.tracks]]
[discs.tracks.metadata]
title = "The Natives Are Restless Tonight"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Calcutta Cutie"

[[discs]]
[discs.metadata]

[[discs.tracks]]
[discs.tracks.metadata]
title = "Que Pasa"

[[discs.tracks]]
[discs.tracks.metadata]
title = "The Kicker"

[[discs.tracks]]
[discs.tracks.metadata]
title = "Lonely Woman (Trio)"

[children]
[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/1.01 - Song for My Father.flac"
disc_number = 1
track_number = 1

[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/1.02 - The Natives Are Restless Tonight.flac"
disc_number = 1
track_number = 2

[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/1.03 - Calcutta Cutie.flac"
disc_number = 1
track_number = 3

[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/2.01 - Que Pasa.flac"
disc_number = 2
track_number = 1

[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/2.02 - The Kicker.flac"
disc_number = 2
track_number = 2

[[children.files]]
file = "Horace Silver - (1964) Song for My Father (Cantiga para meu pai) [2019, MMBST-84185, 33 RPM, Stereo, PBTHAL 2019]/2.03 - Lonely Woman (Trio).flac"
disc_number = 2
track_number = 3
